eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: service-feign
#\u542F\u7528\u65AD\u8DEF\u5668
feign:
  hystrix:
    enabled: true
